/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSupportRouteImport } from './routes/_authed/support'
import { Route as AuthedSubscriptionsRouteImport } from './routes/_authed/subscriptions'
import { Route as AuthedSubscriptionPlansRouteImport } from './routes/_authed/subscription-plans'
import { Route as AuthedShopRouteImport } from './routes/_authed/shop'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedModerationRouteImport } from './routes/_authed/moderation'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedDatabaseRouteImport } from './routes/_authed/database'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAnnouncementsRouteImport } from './routes/_authed/announcements'
import { Route as AuthedAnalyticsRouteImport } from './routes/_authed/analytics'
import { Route as AuthedAiSettingsRouteImport } from './routes/_authed/ai-settings'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSupportRoute = AuthedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSubscriptionsRoute = AuthedSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSubscriptionPlansRoute = AuthedSubscriptionPlansRouteImport.update({
  id: '/subscription-plans',
  path: '/subscription-plans',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShopRoute = AuthedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedModerationRoute = AuthedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDatabaseRoute = AuthedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnnouncementsRoute = AuthedAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalyticsRoute = AuthedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAiSettingsRoute = AuthedAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-settings': typeof AuthedAiSettingsRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/announcements': typeof AuthedAnnouncementsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/database': typeof AuthedDatabaseRoute
  '/members': typeof AuthedMembersRoute
  '/moderation': typeof AuthedModerationRoute
  '/settings': typeof AuthedSettingsRoute
  '/shop': typeof AuthedShopRoute
  '/subscription-plans': typeof AuthedSubscriptionPlansRoute
  '/subscriptions': typeof AuthedSubscriptionsRoute
  '/support': typeof AuthedSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-settings': typeof AuthedAiSettingsRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/announcements': typeof AuthedAnnouncementsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/database': typeof AuthedDatabaseRoute
  '/members': typeof AuthedMembersRoute
  '/moderation': typeof AuthedModerationRoute
  '/settings': typeof AuthedSettingsRoute
  '/shop': typeof AuthedShopRoute
  '/subscription-plans': typeof AuthedSubscriptionPlansRoute
  '/subscriptions': typeof AuthedSubscriptionsRoute
  '/support': typeof AuthedSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/ai-settings': typeof AuthedAiSettingsRoute
  '/_authed/analytics': typeof AuthedAnalyticsRoute
  '/_authed/announcements': typeof AuthedAnnouncementsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/database': typeof AuthedDatabaseRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/moderation': typeof AuthedModerationRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/shop': typeof AuthedShopRoute
  '/_authed/subscription-plans': typeof AuthedSubscriptionPlansRoute
  '/_authed/subscriptions': typeof AuthedSubscriptionsRoute
  '/_authed/support': typeof AuthedSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/ai-settings'
    | '/analytics'
    | '/announcements'
    | '/dashboard'
    | '/database'
    | '/members'
    | '/moderation'
    | '/settings'
    | '/shop'
    | '/subscription-plans'
    | '/subscriptions'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/ai-settings'
    | '/analytics'
    | '/announcements'
    | '/dashboard'
    | '/database'
    | '/members'
    | '/moderation'
    | '/settings'
    | '/shop'
    | '/subscription-plans'
    | '/subscriptions'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/reset-password'
    | '/_authed/ai-settings'
    | '/_authed/analytics'
    | '/_authed/announcements'
    | '/_authed/dashboard'
    | '/_authed/database'
    | '/_authed/members'
    | '/_authed/moderation'
    | '/_authed/settings'
    | '/_authed/shop'
    | '/_authed/subscription-plans'
    | '/_authed/subscriptions'
    | '/_authed/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/support': {
      id: '/_authed/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthedSupportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/subscriptions': {
      id: '/_authed/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthedSubscriptionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/subscription-plans': {
      id: '/_authed/subscription-plans'
      path: '/subscription-plans'
      fullPath: '/subscription-plans'
      preLoaderRoute: typeof AuthedSubscriptionPlansRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/shop': {
      id: '/_authed/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthedShopRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/moderation': {
      id: '/_authed/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthedModerationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/database': {
      id: '/_authed/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthedDatabaseRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/announcements': {
      id: '/_authed/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthedAnnouncementsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics': {
      id: '/_authed/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthedAnalyticsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ai-settings': {
      id: '/_authed/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AuthedAiSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAiSettingsRoute: typeof AuthedAiSettingsRoute
  AuthedAnalyticsRoute: typeof AuthedAnalyticsRoute
  AuthedAnnouncementsRoute: typeof AuthedAnnouncementsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDatabaseRoute: typeof AuthedDatabaseRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedModerationRoute: typeof AuthedModerationRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedShopRoute: typeof AuthedShopRoute
  AuthedSubscriptionPlansRoute: typeof AuthedSubscriptionPlansRoute
  AuthedSubscriptionsRoute: typeof AuthedSubscriptionsRoute
  AuthedSupportRoute: typeof AuthedSupportRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAiSettingsRoute: AuthedAiSettingsRoute,
  AuthedAnalyticsRoute: AuthedAnalyticsRoute,
  AuthedAnnouncementsRoute: AuthedAnnouncementsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDatabaseRoute: AuthedDatabaseRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedModerationRoute: AuthedModerationRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedShopRoute: AuthedShopRoute,
  AuthedSubscriptionPlansRoute: AuthedSubscriptionPlansRoute,
  AuthedSubscriptionsRoute: AuthedSubscriptionsRoute,
  AuthedSupportRoute: AuthedSupportRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
